# Start from golang base image
FROM golang:1.20.1-alpine3.17 as builder

# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git build-base curl

COPY . /app

# Set the current working directory inside the container
WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest

#Command to run the executable
CMD CompileDaemon --build="go build web/main.go" --command="./main" --color
