FROM golang:1.20.1-alpine3.17 as builder

COPY . /app

WORKDIR /app

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

CMD goose -dir "./migrations" ${DB_DRIVER} "user=${DB_USER} password=${DB_PASSWORD} host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} sslmode=${SSL_MODE}" up 

